export const GRAMMAR_VOCAB_CONFIG = {
  skillKey: 'grammar-vocab',
  title: 'GRAMMAR & VOCABULARY TEST',
  parts: ['part1', 'part2'],
  tabs: [
    { id: 'part1', label: 'Part 1' },
    { id: 'part2', label: 'Part 2' },
    { id: 'full', label: 'Full test' },
  ],
  tests: [
    {
      id: 101,
      title: 'Grammar & Vocabulary Practice Set 1',
      desc: 'Multiple-choice language questions\nAptis Practice Test',
      part: 'Part 1',
      tabId: 'part1',
      status: 'Completed',
      submitted: '20:15 - Jan 06, 2026',
      duration: '00:10:30',
      accuracy: 80,
    },
    { id: 102, title: 'Grammar & Vocabulary Practice Set 2', desc: 'Sentence completion\nAptis Practice Test', part: 'Part 1', tabId: 'part1', status: 'Not Started' },
    { id: 103, title: 'Grammar & Vocabulary Practice Set 3', desc: 'Grammar in context\nAptis Practice Test', part: 'Part 1', tabId: 'part1', status: 'Not Started' },
    { id: 104, title: 'Grammar & Vocabulary Practice Set 4', desc: 'Multiple-choice language questions\nAptis Practice Test', part: 'Part 1', tabId: 'part1', status: 'Not Started' },
    { id: 105, title: 'Grammar & Vocabulary Practice Set 5', desc: 'Sentence completion\nAptis Practice Test', part: 'Part 1', tabId: 'part1', status: 'Not Started' },

    {
      id: 201,
      title: 'Grammar & Vocabulary Practice Set 6',
      desc: 'Synonyms and word matching\nAptis Practice Test',
      part: 'Part 2',
      tabId: 'part2',
      status: 'Completed',
      submitted: '18:40 - Feb 12, 2026',
      duration: '00:11:20',
      accuracy: 88,
    },
    { id: 202, title: 'Grammar & Vocabulary Practice Set 7', desc: 'Word definition matching\nAptis Practice Test', part: 'Part 2', tabId: 'part2', status: 'Not Started' },
    { id: 203, title: 'Grammar & Vocabulary Practice Set 8', desc: 'Word pair matching\nAptis Practice Test', part: 'Part 2', tabId: 'part2', status: 'Not Started' },
    { id: 204, title: 'Grammar & Vocabulary Practice Set 9', desc: 'Words in context\nAptis Practice Test', part: 'Part 2', tabId: 'part2', status: 'Not Started' },
    { id: 205, title: 'Grammar & Vocabulary Practice Set 10', desc: 'Synonyms and word matching\nAptis Practice Test', part: 'Part 2', tabId: 'part2', status: 'Not Started' },

    {
      id: 301,
      title: 'Full Grammar & Vocabulary Test 1',
      desc: 'Grammar and vocabulary\n50 questions in 25 minutes',
      part: 'Full Test',
      tabId: 'full',
      status: 'Completed',
      submitted: '09:30 - Mar 05, 2026',
      duration: '00:23:45',
      accuracy: 76,
    },
    { id: 302, title: 'Full Grammar & Vocabulary Test 2', desc: 'Grammar and vocabulary\n50 questions in 25 minutes', part: 'Full Test', tabId: 'full', status: 'Not Started' },
    { id: 303, title: 'Full Grammar & Vocabulary Test 3', desc: 'Grammar and vocabulary\n50 questions in 25 minutes', part: 'Full Test', tabId: 'full', status: 'Not Started' },
    { id: 304, title: 'Full Grammar & Vocabulary Test 4', desc: 'Grammar and vocabulary\n50 questions in 25 minutes', part: 'Full Test', tabId: 'full', status: 'Not Started' },
    { id: 305, title: 'Full Grammar & Vocabulary Test 5', desc: 'Grammar and vocabulary\n50 questions in 25 minutes', part: 'Full Test', tabId: 'full', status: 'Not Started' },
  ],
};
