import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AdminConfirmDialog, AdminValidationToast } from '../components/AdminFeedback';
import { Field } from '../shared-test-builder/BuilderFields';
import ImageField from '../shared-test-builder/ImageField';
import PartSummaryCard from '../writing/components/PartSummaryCard';
import { useSpeakingBuilder } from './context/SpeakingBuilderContext';
import { SPEAKING_PARTS } from './data/speakingTestModel';
import { saveStoredSpeakingTest } from './data/speakingTestStorage';
import { validateSpeakingTest } from './validation/speakingValidation';
import styles from '../writing/WritingTestDetailsPage.module.css';
export default function SpeakingTestDetailsPage(){const{test,updateDetails,basePath}=useSpeakingBuilder();const navigate=useNavigate();const[errors,setErrors]=useState([]);const[confirm,setConfirm]=useState(false);const parts=SPEAKING_PARTS.filter(part=>test.mode==='full'||test.mode===`part${part.number}`);const requestSave=()=>{const next=validateSpeakingTest(test);setErrors(next);if(!next.length)setConfirm(true)};const persist=()=>{try{const saved=saveStoredSpeakingTest(test);navigate(`/admin/tests/speaking/${saved.id}/preview`,{state:{toast:test.id?'Speaking test updated successfully.':'Speaking test created successfully.'}})}catch{setErrors(['Unable to save. Uploaded images may exceed browser storage capacity.'])}finally{setConfirm(false)}};return <div className={styles.page}><AdminValidationToast errors={errors} onClose={()=>setErrors([])}/><AdminConfirmDialog open={confirm} title={test.id?'Save changes to this Speaking test?':'Create Speaking test?'} message="The test will be displayed in Test Management and the candidate Speaking test list." confirmLabel={test.id?'Save changes':'Create test'} onCancel={()=>setConfirm(false)} onConfirm={persist}/><div className={styles.crumb}>Test Management › Admin › {test.details.title||'New Speaking test'}</div><section className={styles.information}><h2>INFORMATION TEST</h2><div className={styles.infoGrid}><div className={styles.fields}><Field label="Title" value={test.details.title} onChange={value=>updateDetails('title',value)}/><ImageField label="Test cover" value={test.details.pictureUrl} onChange={value=>updateDetails('pictureUrl',value)}/></div><aside><b>Preview</b><div><header><span>{test.mode==='full'?'Full test':test.mode.replace('part','Part ')}</span></header>{test.details.pictureUrl?<img src={test.details.pictureUrl} alt="Test cover"/>:<strong>AptiMate<br/><em>Speaking</em></strong>}<button onClick={requestSave}>Preview</button></div></aside></div></section><section className={styles.content}><h2>CONTENT TEST</h2><div>{parts.map(part=><PartSummaryCard key={part.number} part={part} onEdit={()=>navigate(`${basePath}/part/${part.number}`)}/>)}</div><button className={styles.saveAll} onClick={requestSave}>{test.id?'Update test & preview':'Save test & preview'}</button></section></div>}
