export default () => ({
  app: {
    env: process.env.NODE_ENV ?? 'development',
    port: Number(process.env.PORT ?? 3000),
    apiPrefix: process.env.API_PREFIX ?? 'api/v1',
    frontendOrigin: process.env.FRONTEND_ORIGIN,
  },
  database: {
    url: process.env.DATABASE_URL,
    poolMax: Number(process.env.DB_POOL_MAX ?? 10),
    connectTimeoutMs: Number(process.env.DB_CONNECT_TIMEOUT_MS ?? 5000),
    ssl: process.env.DB_SSL === 'true',
  },
  auth: {
    accessSecret: process.env.JWT_ACCESS_SECRET,
    refreshSecret: process.env.JWT_REFRESH_SECRET,
    issuer: process.env.JWT_ISSUER,
    audience: process.env.JWT_AUDIENCE,
    accessTtlSeconds: Number(process.env.ACCESS_TOKEN_TTL_SECONDS ?? 900),
    refreshTtlDays: Number(process.env.REFRESH_TOKEN_TTL_DAYS ?? 7),
    passwordHashRounds: Number(process.env.PASSWORD_HASH_ROUNDS ?? 12),
    resetOtpTtlMinutes: Number(process.env.PASSWORD_RESET_OTP_TTL_MINUTES ?? 10),
    resetGrantTtlMinutes: Number(process.env.PASSWORD_RESET_GRANT_TTL_MINUTES ?? 15),
    resetMaxAttempts: Number(process.env.PASSWORD_RESET_MAX_ATTEMPTS ?? 5),
  },
  smtp: {
    enabled: process.env.SMTP_ENABLED === 'true',
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT ?? 587),
    secure: process.env.SMTP_SECURE === 'true',
    user: process.env.SMTP_USER,
    password: process.env.SMTP_PASSWORD,
    from: process.env.SMTP_FROM,
  },
});
