import * as Joi from 'joi';

export const environmentSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().port().default(3000),
  API_PREFIX: Joi.string().pattern(/^[a-z0-9/-]+$/).default('api/v1'),
  FRONTEND_ORIGIN: Joi.string().uri().required(),
  LOG_LEVEL: Joi.string().valid('log', 'error', 'warn', 'debug', 'verbose').default('log'),
  DATABASE_URL: Joi.string().uri({ scheme: ['postgres', 'postgresql'] }).required(),
  DB_POOL_MAX: Joi.number().integer().min(1).max(100).default(10),
  DB_CONNECT_TIMEOUT_MS: Joi.number().integer().min(500).default(5000),
  DB_SSL: Joi.boolean().truthy('true').falsy('false').default(false),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_REFRESH_SECRET: Joi.string().min(32).required(),
  JWT_ISSUER: Joi.string().required(),
  JWT_AUDIENCE: Joi.string().required(),
  ACCESS_TOKEN_TTL_SECONDS: Joi.number().integer().min(60).default(900),
  REFRESH_TOKEN_TTL_DAYS: Joi.number().integer().min(1).default(7),
  PASSWORD_HASH_ROUNDS: Joi.number().integer().min(10).max(14).default(12),
  PASSWORD_RESET_OTP_TTL_MINUTES: Joi.number().integer().min(3).max(30).default(10),
  PASSWORD_RESET_GRANT_TTL_MINUTES: Joi.number().integer().min(5).max(30).default(15),
  PASSWORD_RESET_MAX_ATTEMPTS: Joi.number().integer().min(3).max(10).default(5),
  SMTP_ENABLED: Joi.boolean().truthy('true').falsy('false').default(false),
  SMTP_HOST: Joi.when('SMTP_ENABLED', { is: true, then: Joi.alternatives(Joi.string().hostname(), Joi.string().ip()).required(), otherwise: Joi.string().allow('') }),
  SMTP_PORT: Joi.number().port().default(587),
  SMTP_SECURE: Joi.boolean().truthy('true').falsy('false').default(false),
  SMTP_USER: Joi.string().allow('').optional(),
  SMTP_PASSWORD: Joi.string().allow('').optional(),
  SMTP_FROM: Joi.when('SMTP_ENABLED', { is: true, then: Joi.string().required(), otherwise: Joi.string().allow('') }),
}).unknown(true);
